/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircularsRouteImport } from './routes/circulars'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ContactsDotRouteImport } from './routes/contacts/dot'
import { Route as ContactsNodalRouteImport } from './routes/contacts/nodal'
import { Route as ImeiIndexRouteImport } from './routes/imei/index'
import { Route as ImeiDotAnalysisRouteImport } from './routes/imei/dot-analysis'
import { Route as ImeiPerformanceRouteImport } from './routes/imei/performance'
import { Route as ImeiSamanvayaRouteImport } from './routes/imei/samanvaya'
import { Route as MobileArchiveRouteImport } from './routes/mobile/archive'
import { Route as MobilePerformanceRouteImport } from './routes/mobile/performance'
import { Route as MobileSamanvayaRouteImport } from './routes/mobile/samanvaya'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as PosPerformanceRouteImport } from './routes/pos/performance'
import { Route as EntityTypeIdRouteImport } from './routes/entity.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsRoute = CircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsDotRoute = ContactsDotRouteImport.update({
  id: '/contacts/dot',
  path: '/contacts/dot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNodalRoute = ContactsNodalRouteImport.update({
  id: '/contacts/nodal',
  path: '/contacts/nodal',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeiIndexRoute = ImeiIndexRouteImport.update({
  id: '/imei/',
  path: '/imei/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeiDotAnalysisRoute = ImeiDotAnalysisRouteImport.update({
  id: '/imei/dot-analysis',
  path: '/imei/dot-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeiPerformanceRoute = ImeiPerformanceRouteImport.update({
  id: '/imei/performance',
  path: '/imei/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeiSamanvayaRoute = ImeiSamanvayaRouteImport.update({
  id: '/imei/samanvaya',
  path: '/imei/samanvaya',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileArchiveRoute = MobileArchiveRouteImport.update({
  id: '/mobile/archive',
  path: '/mobile/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePerformanceRoute = MobilePerformanceRouteImport.update({
  id: '/mobile/performance',
  path: '/mobile/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileSamanvayaRoute = MobileSamanvayaRouteImport.update({
  id: '/mobile/samanvaya',
  path: '/mobile/samanvaya',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosPerformanceRoute = PosPerformanceRouteImport.update({
  id: '/pos/performance',
  path: '/pos/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityTypeIdRoute = EntityTypeIdRouteImport.update({
  id: '/entity/$type/$id',
  path: '/entity/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circulars': typeof CircularsRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/contacts/dot': typeof ContactsDotRoute
  '/contacts/nodal': typeof ContactsNodalRoute
  '/imei/dot-analysis': typeof ImeiDotAnalysisRoute
  '/imei/performance': typeof ImeiPerformanceRoute
  '/imei/samanvaya': typeof ImeiSamanvayaRoute
  '/mobile/archive': typeof MobileArchiveRoute
  '/mobile/performance': typeof MobilePerformanceRoute
  '/mobile/samanvaya': typeof MobileSamanvayaRoute
  '/pos/performance': typeof PosPerformanceRoute
  '/imei/': typeof ImeiIndexRoute
  '/pos/': typeof PosIndexRoute
  '/entity/$type/$id': typeof EntityTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circulars': typeof CircularsRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/contacts/dot': typeof ContactsDotRoute
  '/contacts/nodal': typeof ContactsNodalRoute
  '/imei/dot-analysis': typeof ImeiDotAnalysisRoute
  '/imei/performance': typeof ImeiPerformanceRoute
  '/imei/samanvaya': typeof ImeiSamanvayaRoute
  '/mobile/archive': typeof MobileArchiveRoute
  '/mobile/performance': typeof MobilePerformanceRoute
  '/mobile/samanvaya': typeof MobileSamanvayaRoute
  '/pos/performance': typeof PosPerformanceRoute
  '/imei': typeof ImeiIndexRoute
  '/pos': typeof PosIndexRoute
  '/entity/$type/$id': typeof EntityTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circulars': typeof CircularsRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/registry': typeof RegistryRoute
  '/search': typeof SearchRoute
  '/contacts/dot': typeof ContactsDotRoute
  '/contacts/nodal': typeof ContactsNodalRoute
  '/imei/dot-analysis': typeof ImeiDotAnalysisRoute
  '/imei/performance': typeof ImeiPerformanceRoute
  '/imei/samanvaya': typeof ImeiSamanvayaRoute
  '/mobile/archive': typeof MobileArchiveRoute
  '/mobile/performance': typeof MobilePerformanceRoute
  '/mobile/samanvaya': typeof MobileSamanvayaRoute
  '/pos/performance': typeof PosPerformanceRoute
  '/imei/': typeof ImeiIndexRoute
  '/pos/': typeof PosIndexRoute
  '/entity/$type/$id': typeof EntityTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circulars'
    | '/feedback'
    | '/login'
    | '/registry'
    | '/search'
    | '/contacts/dot'
    | '/contacts/nodal'
    | '/imei/dot-analysis'
    | '/imei/performance'
    | '/imei/samanvaya'
    | '/mobile/archive'
    | '/mobile/performance'
    | '/mobile/samanvaya'
    | '/pos/performance'
    | '/imei/'
    | '/pos/'
    | '/entity/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circulars'
    | '/feedback'
    | '/login'
    | '/registry'
    | '/search'
    | '/contacts/dot'
    | '/contacts/nodal'
    | '/imei/dot-analysis'
    | '/imei/performance'
    | '/imei/samanvaya'
    | '/mobile/archive'
    | '/mobile/performance'
    | '/mobile/samanvaya'
    | '/pos/performance'
    | '/imei'
    | '/pos'
    | '/entity/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/circulars'
    | '/feedback'
    | '/login'
    | '/registry'
    | '/search'
    | '/contacts/dot'
    | '/contacts/nodal'
    | '/imei/dot-analysis'
    | '/imei/performance'
    | '/imei/samanvaya'
    | '/mobile/archive'
    | '/mobile/performance'
    | '/mobile/samanvaya'
    | '/pos/performance'
    | '/imei/'
    | '/pos/'
    | '/entity/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircularsRoute: typeof CircularsRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  RegistryRoute: typeof RegistryRoute
  SearchRoute: typeof SearchRoute
  ContactsDotRoute: typeof ContactsDotRoute
  ContactsNodalRoute: typeof ContactsNodalRoute
  ImeiDotAnalysisRoute: typeof ImeiDotAnalysisRoute
  ImeiPerformanceRoute: typeof ImeiPerformanceRoute
  ImeiSamanvayaRoute: typeof ImeiSamanvayaRoute
  MobileArchiveRoute: typeof MobileArchiveRoute
  MobilePerformanceRoute: typeof MobilePerformanceRoute
  MobileSamanvayaRoute: typeof MobileSamanvayaRoute
  PosPerformanceRoute: typeof PosPerformanceRoute
  ImeiIndexRoute: typeof ImeiIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  EntityTypeIdRoute: typeof EntityTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars': {
      id: '/circulars'
      path: '/circulars'
      fullPath: '/circulars'
      preLoaderRoute: typeof CircularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/dot': {
      id: '/contacts/dot'
      path: '/contacts/dot'
      fullPath: '/contacts/dot'
      preLoaderRoute: typeof ContactsDotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/nodal': {
      id: '/contacts/nodal'
      path: '/contacts/nodal'
      fullPath: '/contacts/nodal'
      preLoaderRoute: typeof ContactsNodalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imei/': {
      id: '/imei/'
      path: '/imei'
      fullPath: '/imei/'
      preLoaderRoute: typeof ImeiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imei/dot-analysis': {
      id: '/imei/dot-analysis'
      path: '/imei/dot-analysis'
      fullPath: '/imei/dot-analysis'
      preLoaderRoute: typeof ImeiDotAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imei/performance': {
      id: '/imei/performance'
      path: '/imei/performance'
      fullPath: '/imei/performance'
      preLoaderRoute: typeof ImeiPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imei/samanvaya': {
      id: '/imei/samanvaya'
      path: '/imei/samanvaya'
      fullPath: '/imei/samanvaya'
      preLoaderRoute: typeof ImeiSamanvayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/archive': {
      id: '/mobile/archive'
      path: '/mobile/archive'
      fullPath: '/mobile/archive'
      preLoaderRoute: typeof MobileArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/performance': {
      id: '/mobile/performance'
      path: '/mobile/performance'
      fullPath: '/mobile/performance'
      preLoaderRoute: typeof MobilePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/samanvaya': {
      id: '/mobile/samanvaya'
      path: '/mobile/samanvaya'
      fullPath: '/mobile/samanvaya'
      preLoaderRoute: typeof MobileSamanvayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/performance': {
      id: '/pos/performance'
      path: '/pos/performance'
      fullPath: '/pos/performance'
      preLoaderRoute: typeof PosPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$type/$id': {
      id: '/entity/$type/$id'
      path: '/entity/$type/$id'
      fullPath: '/entity/$type/$id'
      preLoaderRoute: typeof EntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircularsRoute: CircularsRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  RegistryRoute: RegistryRoute,
  SearchRoute: SearchRoute,
  ContactsDotRoute: ContactsDotRoute,
  ContactsNodalRoute: ContactsNodalRoute,
  ImeiDotAnalysisRoute: ImeiDotAnalysisRoute,
  ImeiPerformanceRoute: ImeiPerformanceRoute,
  ImeiSamanvayaRoute: ImeiSamanvayaRoute,
  MobileArchiveRoute: MobileArchiveRoute,
  MobilePerformanceRoute: MobilePerformanceRoute,
  MobileSamanvayaRoute: MobileSamanvayaRoute,
  PosPerformanceRoute: PosPerformanceRoute,
  ImeiIndexRoute: ImeiIndexRoute,
  PosIndexRoute: PosIndexRoute,
  EntityTypeIdRoute: EntityTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
